### ISSUE TITLE
Actors v5 Plan

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#1391]
# Meta

This issue is a proposal for planning actors v5, which is scheduled to hit mainnet sometime in early June, exact epoch tbd.  Work to be done includes required consensus breaking upgrades and testing improvements, optional consensus breaking upgrades that will be included if finished by all implementations on mainnet, and optional specs-actors non-breaking improvements.

Please leave your feedback in the comments, particularly on things that you expected to see but are missing.

# Changes

## Upgrades

We can't ship v5 until all live implementations have the following:
- [x] FIP 0013 -- aggregate Porep. Issues: #1257, #474 (PR https://github.com/filecoin-project/specs-actors/pull/1381)
- [x] FIP 0008 -- batched Precommit. Issue #1241 
- [x] FIP 0012 -- verified client reuse #1327 (PR https://github.com/filecoin-project/specs-actors/pull/1390)
- [x] FIP 0011 -- consensus fault simplification (PR https://github.com/filecoin-project/specs-actors/pull/1389) 
- [x] market cron randomness offset bug fix #1435 (PR https://github.com/filecoin-project/specs-actors/pull/1439)

Technical debt, optimizations, . We can ship v5 without these fixes but would like to do them now. I'm proposing all implementations work on these after the requirements and then we ship the intersection of all our change sets.  They are roughly in order of difficulty and I plan to work on them in about this order
- [ ] #1332 fix compact partitions bug
- [ ] #1250 correct truncating division
- [ ] #1340 inconsistent state loading
- [ ] #1364 multisig optimization (PR https://github.com/filecoin-project/specs-actors/pull/1365)
- [ ] #1375 more forgiving error handling for multi-deal publishing
- [ ] #992, #799 cron cleanup and optimizations
- [ ] #1248 deal proposal serialization change

## Conformance Testing

We won't ship v5 until specs-actors has the following
- [x] specs-actors test-vector conformance tests and test-vector generation. Issues: #1266

## specs-actors non-breaking changes

We will ship v5 without any of these. We will do as many of these as possible. They are in no particular order:

Logging 
- [ ] #1288, #1060 logging 

Simple cleanups
- [ ] #677 adt.Array:MustGet
- [ ] #1059 Fix Paych Voucher field name
- [ ] #905 sector number allocation cleanup
- [ ] #1052 Remove unused DST
- [ ] #1061 Reorganize static function files
- [ ] #1032, #966, #1006, #1020 non-breaking accounting test and cleanup
- [ ] #1011 power delta
- [ ] #1031 verifreg root becomes singleton

Testing & Validation
- [ ] #1387 fix agent tests
- [ ] #1385 agent test CI
- [ ] #1284 reward actor invariant tests
- [ ] #1286 parallelize state validation checks
- [ ] #936 more sector commitment tests
- [ ] #991 research team's filecoin stories tests

**Comment by anorth** [comment]
I'm assuming #1241 batched pre-commit is excluded intentionally. I agree that porep aggregation needs to come first, but getting both in would probably remove the chain throughput limitation on the onboarding of new power.

I expected #277 terminating AWOL miners to be included.

A few others I'd consider including:
- #1318
- #1326

**Comment by nicola** [comment]
Hey @ZenGround0 fantastic update and very clear messaging, thank you!

**Comment by ZenGround0** [comment]
Added FIP 0008 per @anorth's feedback.

**Comment by jennijuju** [comment]
> Hi,
> 
> I was wondering if you could clarify when to expect actors V4. This issue mention early June but Lotus 1.8 realease which should be release this wednesday mentioned support for actors V4.
> 
> [filecoin-project/lotus#6084 (comment)](https://github.com/filecoin-project/lotus/discussions/6084#discussion-3331970)

@rllola network v12 will upgrade the actor to v4, which is happening this Thursday 6 am UTC, more details can be found [here.](https://github.com/filecoin-project/community/discussions/74#discussioncomment-642326). The timeline of actor v5 is still working in prgress.

**Comment by ZenGround0** [comment]
Note, moving compact partitions bug fix from required for v5 to technical debt

**Comment by BigLep** [comment]
Items in this issue that didn't get completed are likely candidates for v6: https://github.com/filecoin-project/specs-actors/issues/1458
